// Content for the 4 Zero Waste booklets. Each day: cover meta, 8 question-bank Qs,
// an apply activity (pick + draw + sentence frame), 5 match words (我会认), write chars (我会写).
module.exports = [
  // ======================================================= DAY 1 — 垃圾分类
  {
    day: 1, accent: '2C5F2D', coverEmoji: '🗑️',
    topicCn: '垃圾去哪儿了?', topicEn: 'Where Does Our Trash Go?',
    emojiRow: '🗑️   ♻️   🍎   ⚠️',
    questions: [
      { em: '🗑️', cn: '垃圾乱丢, 会怎么样?', en: 'What happens if we litter?',
        opts: [{ cn: '会破坏环境, 变脏变臭', en: 'It harms the environment.' }, { cn: '垃圾自己消失', en: 'Trash disappears by itself.' }, { cn: '没关系', en: 'Nothing happens.' }] },
      { em: '♻️', cn: '旧书本、塑料瓶, 放哪个桶?', en: 'Which bin for old books and bottles?',
        opts: [{ cn: '厨余垃圾桶', en: 'Food bin' }, { cn: '可回收物桶 (蓝)', en: 'Recyclable bin (blue)' }, { cn: '有害垃圾桶', en: 'Hazardous bin' }] },
      { em: '🍎', cn: '香蕉皮、剩饭, 放哪个桶?', en: 'Which bin for banana peels and leftovers?',
        opts: [{ cn: '可回收物桶', en: 'Recyclable bin' }, { cn: '其他垃圾桶', en: 'Other bin' }, { cn: '厨余垃圾桶 (绿)', en: 'Food-waste bin (green)' }] },
      { em: '⚠️', cn: '看到废旧电池, 我们应该?', en: 'What should we do with old batteries?',
        opts: [{ cn: '不要碰, 告诉大人', en: "Don't touch — tell an adult." }, { cn: '自己拿去玩', en: 'Play with them.' }, { cn: '扔进可回收桶', en: 'Put in the recycle bin.' }] },
      { em: '🔋', cn: '废旧电池、过期药品是什么垃圾?', en: 'What kind of trash are batteries and old medicine?',
        opts: [{ cn: '可回收物', en: 'Recyclable' }, { cn: '有害垃圾 (红)', en: 'Hazardous (red)' }, { cn: '厨余垃圾', en: 'Food waste' }] },
      { em: '🗑️', cn: '脏纸巾、塑料包装袋, 放哪个桶?', en: 'Which bin for dirty tissues and plastic wrap?',
        opts: [{ cn: '其他垃圾桶 (灰)', en: 'Other-waste bin (gray)' }, { cn: '可回收物桶', en: 'Recyclable bin' }, { cn: '厨余垃圾桶', en: 'Food bin' }] },
      { em: '🌍', cn: '为什么要把垃圾分类?', en: 'Why do we sort our trash?',
        opts: [{ cn: '为了好玩', en: 'For fun.' }, { cn: '让垃圾变成有用的东西, 保护环境', en: 'So trash becomes useful & we protect nature.' }, { cn: '没有用', en: 'It is useless.' }] },
      { em: '♻️', cn: '可回收物回收以后, 会变成什么?', en: 'What happens to recyclables?',
        opts: [{ cn: '做成新东西', en: 'Made into new things.' }, { cn: '马上消失', en: 'Disappear at once.' }, { cn: '变成垃圾怪', en: 'Become the Trash Monster.' }] },
    ],
    apply: {
      titleCn: '我会分类', titleEn: 'I Can Sort',
      pickCn: '👉 这件垃圾放哪个桶？(选一个)', pickEn: 'Which bin does this trash go in? (Pick one)',
      options: [
        { em: '♻️', cn: '可回收物', en: 'Recyclable' }, { em: '🍎', cn: '厨余垃圾', en: 'Food waste' },
        { em: '⚠️', cn: '有害垃圾', en: 'Hazardous' }, { em: '🗑️', cn: '其他垃圾', en: 'Other waste' },
      ],
      drawCn: '画一件垃圾, 放进对的桶里', frameZh: '“这 是 ______。它 要 放 进 ______ 桶。”', frameEn: '"This is ___. It goes in the ___ bin."',
    },
    match: [
      { cn: '可回收', em: '♻️', en: 'recyclable' }, { cn: '厨余', em: '🍎', en: 'food waste' },
      { cn: '有害', em: '⚠️', en: 'hazardous' }, { cn: '其他', em: '🗑️', en: 'other' }, { cn: '分类', em: '🔀', en: 'to sort' },
    ],
    writeChars: '垃圾 · 分类 · 回收',
  },

  // ======================================================= DAY 2 — 可再生能源
  {
    day: 2, accent: '15659F', coverEmoji: '⚡',
    topicCn: '能量从哪里来?', topicEn: 'Where Does Energy Come From?',
    emojiRow: '☀️   💨   💧   🌍',
    questions: [
      { em: '⚡', cn: '灯、车、电视, 都需要什么?', en: 'What do lights, cars and TVs all need?',
        opts: [{ cn: '能源', en: 'Energy' }, { cn: '玩具', en: 'Toys' }, { cn: '糖果', en: 'Candy' }] },
      { em: '☀️', cn: '太阳能来自哪里?', en: 'Where does solar energy come from?',
        opts: [{ cn: '风', en: 'Wind' }, { cn: '太阳', en: 'The sun' }, { cn: '地下', en: 'Underground' }] },
      { em: '💨', cn: '风能来自什么?', en: 'Where does wind energy come from?',
        opts: [{ cn: '流动的风', en: 'Moving wind' }, { cn: '太阳', en: 'The sun' }, { cn: '石头', en: 'Rocks' }] },
      { em: '💧', cn: '水力发电用的是什么?', en: 'What does hydro power use?',
        opts: [{ cn: '电池', en: 'Batteries' }, { cn: '煤', en: 'Coal' }, { cn: '流动的水', en: 'Moving water' }] },
      { em: '♻️', cn: '太阳能、风能、水力, 用得完吗?', en: 'Solar, wind, hydro — do they run out?',
        opts: [{ cn: '用不完 (可再生)', en: "Never run out (renewable)." }, { cn: '很快用完', en: 'Run out fast.' }, { cn: '有毒', en: 'They are toxic.' }] },
      { em: '🛢️', cn: '煤和石油, 用得完吗?', en: 'Do coal and oil run out?',
        opts: [{ cn: '用不完', en: 'Never run out.' }, { cn: '会用完 (不可再生)', en: 'They run out (non-renewable).' }, { cn: '越用越多', en: 'More when used.' }] },
      { em: '💡', cn: '怎样节约用电?', en: 'How do we save electricity?',
        opts: [{ cn: '一直开着灯', en: 'Keep lights on.' }, { cn: '离开就关灯、关电器', en: 'Turn things off when leaving.' }, { cn: '开更多灯', en: 'Turn on more lights.' }] },
      { em: '🌍', cn: '为什么要用可再生能源?', en: 'Why use renewable energy?',
        opts: [{ cn: '更贵', en: 'It is pricier.' }, { cn: '没有用', en: 'It is useless.' }, { cn: '保护地球, 资源用不完', en: "Protect Earth — it won't run out." }] },
    ],
    apply: {
      titleCn: '我爱可再生能源', titleEn: 'I Love Clean Energy',
      pickCn: '👉 你最喜欢哪种可再生能源？(选一个或多个)', pickEn: 'Which clean energy do you like best? (Pick one or more)',
      options: [
        { em: '☀️', cn: '太阳能', en: 'Solar' }, { em: '💨', cn: '风能', en: 'Wind' },
        { em: '💧', cn: '水力', en: 'Hydro' }, { em: '🌱', cn: '节约能源', en: 'Save energy' },
      ],
      drawCn: '画一个用太阳能的东西 (太阳能小车 / 太阳能板)', frameZh: '“我 最 喜 欢 ______ 能。我 会 节 约 ______。”', frameEn: '"I like ___ energy best. I will save ___."',
    },
    match: [
      { cn: '地球', em: '🌍', en: 'Earth' }, { cn: '资源', em: '⛏️', en: 'resources' },
      { cn: '能源', em: '⚡', en: 'energy' }, { cn: '太阳能', em: '☀️', en: 'solar' }, { cn: '节约', em: '💡', en: 'save' },
    ],
    writeChars: '地球 · 节约',
  },

  // ======================================================= DAY 3 — 水与塑料
  {
    day: 3, accent: '0B5563', coverEmoji: '🌊',
    topicCn: '水与塑料', topicEn: 'Water & Plastic — Ocean Guardians',
    emojiRow: '💧   🌊   🐢   🥤   🛡️',
    questions: [
      { em: '💧', cn: '地球上能喝的淡水, 多不多?', en: 'Is there a lot of drinkable fresh water?',
        opts: [{ cn: '很少, 要珍惜', en: 'Very little — we must save it.' }, { cn: '很多, 随便用', en: 'Plenty — use freely.' }, { cn: '一点都没有', en: 'None at all.' }] },
      { em: '🌊', cn: '塑料垃圾最后会去哪里?', en: 'Where does plastic trash end up?',
        opts: [{ cn: '自己消失', en: 'Disappears.' }, { cn: '流进河和海', en: 'Into rivers and the sea.' }, { cn: '变成鱼', en: 'Turns into fish.' }] },
      { em: '🐢', cn: '海洋动物会把塑料当成什么?', en: 'What do sea animals mistake plastic for?',
        opts: [{ cn: '玩具', en: 'Toys' }, { cn: '家', en: 'A home' }, { cn: '食物, 误食会受伤', en: 'Food — eating it hurts them.' }] },
      { em: '🥤', cn: '什么是一次性塑料?', en: 'What is single-use plastic?',
        opts: [{ cn: '用一次就扔的 (吸管/塑料袋)', en: 'Used once then tossed (straws/bags).' }, { cn: '能用很多年的', en: 'Used for years.' }, { cn: '可以吃的', en: 'You can eat it.' }] },
      { em: '♻️', cn: '一次性 和 可重复使用, 哪个更好?', en: 'Single-use or reusable — which is better?',
        opts: [{ cn: '一次性更好', en: 'Single-use is better.' }, { cn: '可重复使用更好', en: 'Reusable is better.' }, { cn: '一样', en: 'Same.' }] },
      { em: '🛍️', cn: '怎样减少塑料垃圾?', en: 'How do we make less plastic trash?',
        opts: [{ cn: '用更多塑料袋', en: 'Use more plastic bags.' }, { cn: '自带水壶和购物袋', en: 'Bring own bottle and bag.' }, { cn: '把塑料扔进海里', en: 'Throw plastic in the sea.' }] },
      { em: '🚰', cn: '刷牙的时候, 我们应该?', en: 'When brushing teeth we should…',
        opts: [{ cn: '关掉水龙头', en: 'Turn off the tap.' }, { cn: '让水一直流', en: 'Let water run.' }, { cn: '用很多很多水', en: 'Use lots of water.' }] },
      { em: '🛡️', cn: '海洋小卫士可以做什么?', en: 'What can an Ocean Guardian do?',
        opts: [{ cn: '乱扔垃圾', en: 'Litter.' }, { cn: '捉海龟', en: 'Catch turtles.' }, { cn: '减少塑料, 保护海洋', en: 'Cut plastic, protect the sea.' }] },
    ],
    apply: {
      titleCn: '海洋小卫士', titleEn: 'Ocean Guardian',
      pickCn: '👉 你可以怎样保护海洋？(选一个或多个)', pickEn: 'How can you protect the ocean? (Pick one or more)',
      options: [
        { em: '🥤', cn: '不用一次性塑料', en: 'No single-use plastic' }, { em: '🛍️', cn: '自带购物袋', en: 'Bring own bag' },
        { em: '🚰', cn: '节约用水', en: 'Save water' }, { em: '🗑️', cn: '不乱扔垃圾', en: 'No littering' },
      ],
      drawCn: '画一画: 你怎样保护海洋', frameZh: '“我 是 海 洋 小 卫 士, 我 可 以 ______。”', frameEn: '"I am an Ocean Guardian. I can ___."',
    },
    match: [
      { cn: '水', em: '💧', en: 'water' }, { cn: '海洋', em: '🌊', en: 'ocean' },
      { cn: '塑料', em: '🥤', en: 'plastic' }, { cn: '污染', em: '🛢️', en: 'pollution' }, { cn: '保护', em: '🛡️', en: 'protect' },
    ],
    writeChars: '水 · 保护 · 塑料',
  },

  // ======================================================= DAY 4 — 家庭 Zero Waste 计划
  {
    day: 4, accent: '2C5F2D', coverEmoji: '🏠',
    topicCn: '家庭 Zero Waste 计划', topicEn: "Our Family's Zero-Waste Plan",
    emojiRow: '⬇️   🔄   🙅   ♻️   🍂',
    questions: [
      { em: '🌍', cn: '“零废弃”是什么意思?', en: 'What does Zero Waste mean?',
        opts: [{ cn: '尽量少产生垃圾', en: 'Make as little trash as possible.' }, { cn: '扔很多垃圾', en: 'Throw out lots of trash.' }, { cn: '不吃东西', en: "Don't eat." }] },
      { em: '🍽️', cn: '还能用却扔掉, 叫什么?', en: 'Throwing away things still usable is called…',
        opts: [{ cn: '环保', en: 'Eco-friendly' }, { cn: '浪费', en: 'Wasteful' }, { cn: '分类', en: 'Sorting' }] },
      { em: '⬇️', cn: '“减少”是什么意思?', en: 'What does 减少 (reduce) mean?',
        opts: [{ cn: '用得更少', en: 'Use less.' }, { cn: '用得更多', en: 'Use more.' }, { cn: '马上扔掉', en: 'Toss it now.' }] },
      { em: '🔄', cn: '自带购物袋、旧瓶子再用, 是哪个 R?', en: 'Reusing bags and jars is which R?',
        opts: [{ cn: '拒绝 Refuse', en: 'Refuse' }, { cn: '堆肥 Rot', en: 'Rot' }, { cn: '重复使用 Reuse', en: 'Reuse' }] },
      { em: '🙅', cn: '5R 里最好的一招 (一开始就不要), 是?', en: "The best R (don't take it at all) is…",
        opts: [{ cn: '拒绝 Refuse', en: 'Refuse' }, { cn: '回收 Recycle', en: 'Recycle' }, { cn: '堆肥 Rot', en: 'Rot' }] },
      { em: '💧', cn: '看到水龙头一直开着, 我们家可以?', en: 'If the tap is left running, our family can…',
        opts: [{ cn: '不管它', en: 'Ignore it.' }, { cn: '随手关水', en: 'Turn it off.' }, { cn: '开得更大', en: 'Open it more.' }] },
      { em: '🍂', cn: '果皮、菜叶埋进土里变肥料, 叫?', en: 'Peels and leaves made into fertilizer is…',
        opts: [{ cn: '回收 Recycle', en: 'Recycle' }, { cn: '浪费 Waste', en: 'Waste' }, { cn: '堆肥 Rot', en: 'Rot / Compost' }] },
      { em: '🛍️', cn: '“购物袋”是用来做什么的?', en: 'What is a 购物袋 (shopping bag) for?',
        opts: [{ cn: '装东西, 可以重复使用', en: 'Carrying things — reusable.' }, { cn: '吃的', en: 'Eating.' }, { cn: '玩的', en: 'Playing.' }] },
    ],
    apply: {
      titleCn: '我们家的计划', titleEn: 'Our Family Plan',
      pickCn: '👉 我们家可以做哪些环保的事？(选一个或多个)', pickEn: 'What can our family do? (Pick one or more)',
      options: [
        { em: '⬇️', cn: '减少 — 自带水壶', en: 'Reduce — own bottle' }, { em: '🔄', cn: '重复使用 — 自带购物袋', en: 'Reuse — own bag' },
        { em: '🙅', cn: '拒绝 — 不要塑料吸管', en: 'Refuse — no straws' }, { em: '🍂', cn: '堆肥 — 果皮变肥料', en: 'Rot — compost peels' },
      ],
      drawCn: '画一画: 我们家的 Zero Waste 计划海报', frameZh: '“我 们 家 可 以 ______。”', frameEn: '"Our family can ___."',
    },
    match: [
      { cn: '减少', em: '⬇️', en: 'reduce' }, { cn: '重复使用', em: '🔄', en: 'reuse' },
      { cn: '环保', em: '🌱', en: 'eco' }, { cn: '购物袋', em: '🛍️', en: 'shopping bag' }, { cn: '浪费', em: '🍽️', en: 'waste' },
    ],
    writeChars: '减少 · 环保',
  },
];
